# Generated by Django 5.2.17 on 2026-09-29 01:20

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        VectorExtension(),
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drawing_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="図番"
                    ),
                ),
                (
                    "revision",
                    models.CharField(blank=True, max_length=16, verbose_name="改訂"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="品名"),
                ),
                (
                    "material",
                    models.CharField(blank=True, max_length=128, verbose_name="材質"),
                ),
                (
                    "scale",
                    models.CharField(blank=True, max_length=32, verbose_name="尺度"),
                ),
                (
                    "drawn_date",
                    models.CharField(blank=True, max_length=32, verbose_name="作成日"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("attrib", "DXF属性"),
                            ("text", "PDFテキスト層"),
                            ("ocr", "OCR"),
                            ("filename", "ファイル名"),
                        ],
                        default="text",
                        max_length=16,
                        verbose_name="読み取り元",
                    ),
                ),
                ("confidence", models.FloatField(default=1.0, verbose_name="信頼度")),
                (
                    "needs_ocr",
                    models.BooleanField(default=False, verbose_name="OCR待ち"),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="その他の属性"
                    ),
                ),
                (
                    "thumbnail",
                    models.CharField(
                        blank=True,
                        help_text="MEDIA_ROOT からの相対パス",
                        max_length=255,
                    ),
                ),
                ("search_text", models.TextField(blank=True)),
                ("parsed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "図面",
                "verbose_name_plural": "図面",
                "ordering": ["drawing_no", "revision"],
            },
        ),
        migrations.CreateModel(
            name="HouseFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_drawing_no",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="基本図番"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=64, verbose_name="型式"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="間口"
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="奥行"
                    ),
                ),
            ],
            options={
                "verbose_name": "派生系統",
                "verbose_name_plural": "派生系統",
            },
        ),
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="共有フォルダからの相対パス（/ 区切り）",
                        max_length=1024,
                        unique=True,
                        verbose_name="パス",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("dxf", "DXF"), ("pdf", "PDF")],
                        max_length=8,
                        verbose_name="種類",
                    ),
                ),
                ("size", models.BigIntegerField(verbose_name="サイズ")),
                ("mtime", models.DateTimeField(verbose_name="更新日時")),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "解析待ち"),
                            ("done", "解析済み"),
                            ("error", "エラー"),
                            ("missing", "見つからない"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終確認"
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ファイル",
                "verbose_name_plural": "ファイル",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "閲覧"),
                            ("download", "ダウンロード"),
                            ("export", "出力"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target", models.CharField(max_length=1024)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "監査ログ",
                "verbose_name_plural": "監査ログ",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="DictionaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(db_index=True, max_length=128, verbose_name="語"),
                ),
                (
                    "canonical",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="代表語"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("synonym", "同義語"),
                            ("ocr_fix", "OCR補正"),
                            ("abbr", "略称"),
                        ],
                        default="synonym",
                        max_length=16,
                        verbose_name="種類",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("rule", "ルール"),
                            ("llm", "Ollama提案"),
                            ("human", "人が登録"),
                        ],
                        default="human",
                        max_length=16,
                        verbose_name="出どころ",
                    ),
                ),
                ("approved", models.BooleanField(default=False, verbose_name="承認")),
            ],
            options={
                "verbose_name": "辞書",
                "verbose_name_plural": "辞書",
                "unique_together": {("term", "canonical")},
            },
        ),
        migrations.CreateModel(
            name="BomItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveIntegerField(verbose_name="行")),
                (
                    "item_no",
                    models.CharField(blank=True, max_length=16, verbose_name="No."),
                ),
                (
                    "part_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="品番"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="品名"),
                ),
                (
                    "qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="数量",
                    ),
                ),
                (
                    "material",
                    models.CharField(blank=True, max_length=128, verbose_name="材質"),
                ),
                (
                    "ref_drawing_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="図番"
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=1.0, verbose_name="信頼度")),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="確認済み"),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_items",
                        to="drawings.drawing",
                    ),
                ),
            ],
            options={
                "verbose_name": "部品表の行",
                "verbose_name_plural": "部品表の行",
                "ordering": ["drawing", "row"],
            },
        ),
        migrations.CreateModel(
            name="HouseSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage",
                    models.CharField(blank=True, max_length=64, verbose_name="用途"),
                ),
                ("windows", models.PositiveIntegerField(default=0, verbose_name="窓")),
                ("doors", models.PositiveIntegerField(default=0, verbose_name="ドア")),
                (
                    "shutters",
                    models.PositiveIntegerField(default=0, verbose_name="シャッター"),
                ),
                (
                    "partitions",
                    models.PositiveIntegerField(default=0, verbose_name="間仕切り"),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=list, verbose_name="仕様・オプション"
                    ),
                ),
                (
                    "drawing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec",
                        to="drawings.drawing",
                    ),
                ),
            ],
            options={
                "verbose_name": "ハウス仕様",
                "verbose_name_plural": "ハウス仕様",
            },
        ),
        migrations.AddField(
            model_name="drawing",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing",
                to="drawings.sourcefile",
            ),
        ),
        migrations.CreateModel(
            name="Derivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        choices=[
                            ("branch_no", "図番の枝番・接尾辞"),
                            ("note", "表題欄・注記"),
                            ("path", "フォルダ・ファイル名"),
                            ("manual", "手動"),
                        ],
                        max_length=16,
                    ),
                ),
                ("evidence", models.CharField(blank=True, max_length=255)),
                ("confidence", models.FloatField(default=1.0)),
                ("verified", models.BooleanField(default=False)),
                (
                    "base_drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_from_me",
                        to="drawings.drawing",
                    ),
                ),
                (
                    "derived_drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivations",
                        to="drawings.drawing",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivations",
                        to="drawings.housefamily",
                    ),
                ),
            ],
            options={
                "verbose_name": "派生",
                "verbose_name_plural": "派生",
                "unique_together": {("base_drawing", "derived_drawing")},
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_no", models.PositiveIntegerField(default=1)),
                ("text", models.TextField(blank=True)),
                (
                    "text_source",
                    models.CharField(
                        choices=[
                            ("attrib", "DXF属性"),
                            ("text", "PDFテキスト層"),
                            ("ocr", "OCR"),
                            ("filename", "ファイル名"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="drawings.drawing",
                    ),
                ),
            ],
            options={
                "ordering": ["page_no"],
                "unique_together": {("drawing", "page_no")},
            },
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bom_ref", "部品表の図番"),
                            ("note_ref", "参照図の記載"),
                            ("derived", "派生元・派生"),
                            ("revision", "改訂系列"),
                            ("common_part", "共通部品"),
                            ("series", "図番の系列"),
                            ("similar", "内容の類似"),
                        ],
                        max_length=16,
                    ),
                ),
                ("weight", models.FloatField(default=0.5)),
                ("evidence", models.CharField(blank=True, max_length=255)),
                (
                    "from_drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_out",
                        to="drawings.drawing",
                    ),
                ),
                (
                    "to_drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_in",
                        to="drawings.drawing",
                    ),
                ),
            ],
            options={
                "verbose_name": "関連",
                "verbose_name_plural": "関連",
                "unique_together": {("from_drawing", "to_drawing", "kind")},
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("parse", "解析"),
                            ("ocr", "OCR"),
                            ("llm", "LLM構造化"),
                            ("embed", "ベクトル化"),
                        ],
                        default="parse",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "待ち"),
                            ("running", "実行中"),
                            ("done", "完了"),
                            ("failed", "失敗"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=100, help_text="小さいほど先に処理"),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("worker", models.CharField(blank=True, max_length=64)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="drawings.sourcefile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ジョブ",
                "verbose_name_plural": "ジョブ",
                "indexes": [
                    models.Index(
                        fields=["state", "priority", "id"],
                        name="drawings_jo_state_356c3c_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="drawing",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_text"],
                name="drawing_search_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
