# Generated by Django 5.2.17 on 2026-09-29 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="page_no",
            field=models.PositiveIntegerField(
                default=1,
                help_text="図面一式の PDF で、この図面が載っているページ",
                verbose_name="ページ",
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawings",
                to="drawings.sourcefile",
            ),
        ),
        migrations.AddConstraint(
            model_name="drawing",
            constraint=models.UniqueConstraint(
                fields=("file", "page_no"), name="drawing_file_page_unique"
            ),
        ),
    ]
