# Generated by Django 5.2.17 on 2026-09-30 01:56

from django.db import migrations, models


def backfill(apps, schema_editor):
    from drawings import classify
    Drawing = apps.get_model("drawings", "Drawing")
    batch = []
    for d in Drawing.objects.select_related("file").iterator(chunk_size=2000):
        classify.apply(d, text="")
        batch.append(d)
        if len(batch) >= 2000:
            Drawing.objects.bulk_update(batch, ["model_family", "model_code", "series_prefix", "series"])
            batch = []
    if batch:
        Drawing.objects.bulk_update(batch, ["model_family", "model_code", "series_prefix", "series"])


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0002_drawing_per_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="model_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="型式"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="model_family",
            field=models.CharField(
                blank=True, db_index=True, max_length=16, verbose_name="型式系統"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="series",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="図番の系列"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="series_prefix",
            field=models.CharField(
                blank=True, db_index=True, max_length=16, verbose_name="図番の頭"
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
