# Generated by Django 5.2.17 on 2026-09-30 02:21

from django.db import migrations, models

GROUPS = ("Admin", "User", "Guest")


def backfill(apps, schema_editor):
    """既存の図面に文書種別を付ける（ページ本文の先頭 3 ページ分も使う）。"""
    from drawings import classify
    Drawing = apps.get_model("drawings", "Drawing")
    Page = apps.get_model("drawings", "Page")
    fields = ["doc_type", "model_family", "model_code", "series_prefix", "series"]
    ids = list(Drawing.objects.order_by("id").values_list("id", flat=True))
    for i in range(0, len(ids), 1000):
        chunk = ids[i:i + 1000]
        texts = {}
        for did, no, text in Page.objects.filter(drawing_id__in=chunk).order_by("drawing_id", "page_no").values_list(
                "drawing_id", "page_no", "text"):
            if len(texts.setdefault(did, [])) < 3:
                texts[did].append((text or "")[:3000])
        batch = list(Drawing.objects.filter(id__in=chunk).select_related("file"))
        for d in batch:
            classify.apply(d, text="\n".join(texts.get(d.id, [])))
        Drawing.objects.bulk_update(batch, fields)


def create_groups(apps, schema_editor):
    """Admin・User・Guest の 3 グループを作り、既存の管理者（superuser）を Admin に入れる。"""
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")
    for name in GROUPS:
        Group.objects.get_or_create(name=name)
    admin = Group.objects.get(name="Admin")
    for u in User.objects.filter(is_superuser=True):
        u.groups.add(admin)


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("drawings", "0003_drawing_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("drawing", "製品図面"),
                    ("site", "敷地・土地図"),
                    ("contract", "契約書・見積"),
                    ("application", "申請書類"),
                    ("other", "その他"),
                ],
                db_index=True,
                default="other",
                help_text="classify.py で自動判定。ゲストは「製品図面」だけ見られる",
                max_length=16,
                verbose_name="文書種別",
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="doc_type_fixed",
            field=models.BooleanField(default=False, help_text="管理画面で種別を直すと付く。付いていると自動判定で上書きしない",
                                      verbose_name="種別を手で確定"),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.RunPython(create_groups, migrations.RunPython.noop),
    ]
