# Generated by Django 5.2.17 on 2026-09-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0004_doc_type_and_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("drawing", "製品図面"),
                    ("site", "敷地・土地図"),
                    ("contract", "契約書・見積"),
                    ("application", "申請書類"),
                    ("general", "一般書類"),
                    ("other", "その他"),
                ],
                db_index=True,
                default="other",
                help_text="classify.py で自動判定。ゲストは「製品図面」だけ見られる",
                max_length=16,
                verbose_name="文書種別",
            ),
        ),
    ]
