# Generated by Django 5.2.17 on 2026-09-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0005_doc_type_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="length",
            field=models.CharField(blank=True, max_length=32, verbose_name="長さ"),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="note",
            field=models.CharField(blank=True, max_length=255, verbose_name="備考"),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="thickness",
            field=models.CharField(blank=True, max_length=32, verbose_name="厚さ"),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="width",
            field=models.CharField(blank=True, max_length=32, verbose_name="幅"),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="ref_drawing_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="この行の部品の図面の図番（関連図面）",
                max_length=64,
                verbose_name="図番",
            ),
        ),
    ]
